# Generated by Django 5.2.1 on 2025-05-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of the student', max_length=100)),
                ('student_id', models.CharField(help_text='Unique identifier for the student', max_length=20, unique=True)),
                ('date_of_birth', models.DateField(help_text='Date of birth of the student')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], help_text='Gender of the student', max_length=10)),
                ('address', models.TextField(help_text='Home address of the student')),
                ('guardian_name', models.CharField(help_text="Name of the student's guardian", max_length=100)),
                ('guardian_contact', models.CharField(help_text='Contact number of the guardian', max_length=20)),
                ('grade', models.CharField(help_text='Grade the student is currently enrolled in', max_length=10)),
                ('classroom', models.CharField(help_text='Classroom or section of the student', max_length=10)),
                ('image', models.ImageField(blank=True, help_text='Photograph of the student', null=True, upload_to='student_images/')),
            ],
        ),
    ]
