# Generated by Django 5.2.1 on 2025-05-09 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gatepass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time the gatepass was requested')),
                ('date_from', models.DateTimeField(help_text='Start date and time for the gatepass')),
                ('date_to', models.DateTimeField(help_text='End date and time for the gatepass')),
                ('is_allowed', models.BooleanField(default=False, help_text='Indicates if the student is allowed to leave')),
                ('date_approved', models.DateTimeField(blank=True, help_text='Date and time when the gatepass was approved', null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved the gatepass', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_gatepasses', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Student requesting the gatepass', on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='GateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(blank=True, help_text='Time when the student entered', null=True)),
                ('gatepass', models.OneToOneField(help_text='The gatepass being logged', on_delete=django.db.models.deletion.CASCADE, to='gatepass.gatepass')),
            ],
        ),
    ]
