# Generated by Django 5.2.1 on 2025-05-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatepass',
            name='is_allowed',
        ),
        migrations.AddField(
            model_name='gatepass',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text="Indicates if the student's gatepass is suspended"),
        ),
    ]
