# Generated by Django 5.2.1 on 2025-05-09 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0002_remove_gatepass_is_allowed_gatepass_is_suspended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatepass',
            name='approved_by',
        ),
        migrations.AlterField(
            model_name='gatelog',
            name='entry_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2025, 5, 9, 13, 53, 19, 448812, tzinfo=datetime.timezone.utc), help_text='Time when the student entered'),
            preserve_default=False,
        ),
    ]
