# Generated by Django 5.2.1 on 2025-05-09 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0003_remove_gatepass_approved_by_alter_gatelog_entry_time'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatelog',
            name='gatepass',
            field=models.OneToOneField(help_text='The student being logged', on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
