# Generated by Django 5.2.1 on 2025-05-09 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0004_alter_gatelog_gatepass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gatelog',
            old_name='gatepass',
            new_name='student',
        ),
    ]
