# Generated by Django 5.2.1 on 2025-05-10 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0005_rename_gatepass_gatelog_student'),
        ('students', '0002_remove_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatelog',
            name='student',
            field=models.ForeignKey(help_text='The student being logged', on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
